import { Router } from "express";
import usersRouter from './users.js';
import analyseRouter from './analyse.js';
import patientRouter from './patient.js';
import doctorRouter from './doctor.js';
import isalab from "../utils/isalab.js";
const router = Router();
router.use(usersRouter);
router.use(patientRouter);
router.use(doctorRouter);
router.use("/lab", isalab, analyseRouter);
export default router;